import 'package:flutter/foundation.dart';
import 'package:dio/dio.dart';
import '../config/api_config.dart';
import '../services/api_service.dart';
import '../services/storage_service.dart';
import '../services/crypto_service.dart';

// ignore_for_file: avoid_print

class AuthProvider extends ChangeNotifier {
  bool _isLoggedIn = false;
  bool _loading    = false;
  bool _isAdmin    = false;
  String? _error;

  bool get isLoggedIn => _isLoggedIn;
  bool get loading    => _loading;
  bool get isAdmin    => _isAdmin;
  String? get error   => _error;

  /// Called at splash to check if a JWT is already stored.
  Future<void> checkAuthState() async {
    final token = await StorageService.getToken();
    _isLoggedIn = token != null;
    if (_isLoggedIn) {
      _isAdmin = await StorageService.getIsAdmin();
    }
    notifyListeners();
  }

  Future<bool> register({
    required String email,
    required String password,
  }) async {
    _loading = true;
    _error   = null;
    notifyListeners();

    try {
      // Generate a fresh key pair for every new registration
      print('[AUTH] Generating RSA key pair...');
      final kp = await CryptoService.generateRsaKeyPair();
      print('[AUTH] Key pair generated. Public key starts with: ${kp['publicKey']?.substring(0, 40)}');

      print('[AUTH] Posting to ${ApiConfig.baseUrl}${ApiConfig.register}');
      final res = await ApiService.dio.post(ApiConfig.register, data: {
        'email':      email,
        'password':   password,
        'public_key': kp['publicKey'],
      });

      print('[AUTH] Register response ${res.statusCode}: ${res.data}');
      final userId = res.data['user_id'] as int;
      await StorageService.saveUserId(userId);
      await StorageService.saveKeyPair(userId, kp['privateKey']!, kp['publicKey']!);

      return true;
    } on DioException catch (e) {
      print('[AUTH] DioException: ${e.type} | status: ${e.response?.statusCode} | data: ${e.response?.data} | message: ${e.message}');
      _error = (e.response?.data as Map?)?['error'] ?? 'Registration failed. (${e.type.name})';
      return false;
    } catch (e, st) {
      print('[AUTH] Unexpected error: $e\n$st');
      _error = 'Error: $e';
      return false;
    } finally {
      _loading = false;
      notifyListeners();
    }
  }

  Future<bool> login({
    required String email,
    required String password,
  }) async {
    _loading = true;
    _error   = null;
    notifyListeners();

    try {
      final res = await ApiService.dio.post(ApiConfig.login, data: {
        'email':    email,
        'password': password,
      });

      final token  = res.data['token'] as String;
      final userId = res.data['user_id'] as int;
      _isAdmin = res.data['is_admin'] == true;

      await StorageService.saveToken(token);
      await StorageService.saveUserId(userId);
      await StorageService.saveIsAdmin(_isAdmin);

      // Ensure this user has a key pair on this device.
      if (!await StorageService.hasKeyPair()) {
        // Try to migrate the legacy (pre-userId) key pair first.
        // These were generated by SubtleCrypto so they work with it,
        // and the server already has the matching public key.
        final legacy = await StorageService.getLegacyKeyPair();
        if (legacy != null && (legacy['privateKey']?.contains('BEGIN PRIVATE KEY') ?? false)) {
          // Migrate to per-user storage — no new key upload needed (server already has it).
          await StorageService.saveKeyPair(userId, legacy['privateKey']!, legacy['publicKey']!);
          await StorageService.clearLegacyKeyPair();
        } else {
          // No usable legacy key — generate a fresh pair and upload the public key.
          final kp = await CryptoService.generateRsaKeyPair();
          await StorageService.saveKeyPair(userId, kp['privateKey']!, kp['publicKey']!);
          await ApiService.dio.put(
            ApiConfig.updatePublicKey,
            data: {'public_key': kp['publicKey']},
          );
        }
      }

      _isLoggedIn = true;
      return true;
    } on DioException catch (e) {
      _error = (e.response?.data as Map?)?['error'] ?? 'Login failed.';
      return false;
    } finally {
      _loading = false;
      notifyListeners();
    }
  }

  Future<void> logout() async {
    await StorageService.clearSession(); // keeps RSA keys so old shares stay decryptable
    _isLoggedIn = false;
    _isAdmin    = false;
    notifyListeners();
  }
}
